// Augments the generated cloudflare-env.d.ts (see AGENTS.md — that file is
// regenerated by `npm run cf:typegen` and only knows about wrangler.jsonc
// bindings). Secrets set via `wrangler secret put` / .dev.vars never appear
// there, so they're declared here instead via TypeScript's global interface
// merging.
interface CloudflareEnv {
  /** Bearer token required by the public /api/* scraper-proxy routes. See lib/apiAuth.ts. */
  API_TOKEN?: string;
}
